Output example2.gif

Set TypingSpeed 30ms
Set FontFamily "Cartograph CF"
Set FontSize 15
Set Width 1280
Set Height 720
Set Theme "Desert"

Type "cd .."

Enter

Type "go run cmd/goread/main.go"

Enter

# Wait for the program to start
Sleep 1s

# Select technology
Type "j"

Sleep 3s

Enter

# Wait until the category is loaded
Sleep 5s

Type "1"

# Wait until the feed is loaded
Sleep 3s

Enter

Sleep 5s
